name: Functional tests

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOLOKA_TOKEN: ${{ secrets.TOLOKA_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Run tox with Python 3.8
      id: tests
      continue-on-error: true
      run: |
        python -m tox -e py38-functional-tests
    - uses: octokit/request-action@v2.x
      with:
        route: POST /repos/{owner}/{repo}/statuses/{sha}
        owner: toloka
        repo: toloka-kit
        sha: ${{ github.sha }}
        state: ${{ steps.tests.outcome == 'success' && 'success' || 'failure' }}
        description: pending functional tests run
        context: Functional tests check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
